"""empty message

Revision ID: b53d871d3f07
Revises: 
Create Date: 2019-10-06 13:05:12.719743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53d871d3f07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('target_text', sa.Text(), nullable=True),
    sa.Column('source_language', sa.String(length=255), nullable=True),
    sa.Column('target_language', sa.String(length=255), nullable=True),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    # ### end Alembic commands ###
